services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8976:80"
    container_name: project_nginx
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    depends_on:
      - db
    container_name: project_app 
  
  db:
    image: postgres
    restart: always
    volumes: 
      - ./tmp/db:/var/lib/pgsql
    environment:
      POSTGRES_DB: lardocker
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "8101:5432"
    container_name: project_db